# Generated by Django 4.0.3 on 2022-04-18 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='dep_name',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Doctors',
        ),
    ]
