# Generated by Django 4.0.3 on 2022-04-22 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
